name: loan_application
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  camera: ^0.10.5+2
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  encrypt: ^5.0.3
  google_maps_flutter: ^2.12.2
  url_launcher: ^6.3.1
  geolocator: ^14.0.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_multi_formatter: ^2.13.7
  get: ^4.7.2
  get_storage: ^2.1.1
  image: ^4.1.3
  image_picker: ^1.0.4
  intl: ^0.20.2
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  json_annotation: ^4.9.0
  permission_handler: ^12.0.0+1
  country_code_picker: ^3.3.0
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/outfitmedium.ttf
        - asset: assets/fonts/outfitregular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: EricaOne
      fonts:
        - asset: assets/fonts/Ericaone-Regular.ttf
